import * as cdk from 'aws-cdk-lib';
import { Template, Match } from 'aws-cdk-lib/assertions';
import * as fc from 'fast-check';
import { RegionalStack } from '../lib/regional-stack';
import { DeploymentConfig } from '../lib/config';

/**
 * Feature: cdk-open-source-refactor, Property 3: Project name prefix propagation
 *
 * For any valid project name, all AWS resource names/identifiers generated by
 * the CDK stacks should contain that project name as a prefix.
 *
 * Validates: Requirements 5.2
 */

// --- Helper: create a minimal valid config ---
function createConfig(overrides: Partial<DeploymentConfig> = {}): DeploymentConfig {
  return {
    projectName: 'test-project',
    primaryRegion: 'us-east-1',
    emailRestriction: { enabled: false },
    mfa: 'optional',
    ...overrides,
  };
}

// --- Helper: synthesize a RegionalStack and return the template ---
function synthesizeRegionalStack(config: DeploymentConfig, allowedOrigin?: string): Template {
  const app = new cdk.App();
  const stack = new RegionalStack(app, 'TestRegionalStack', {
    config,
    allowedOrigin,
    env: { region: config.primaryRegion, account: '123456789012' },
  });
  return Template.fromStack(stack);
}

// --- Generators ---

/** Generate a valid project name: starts with a letter, followed by alphanumeric/hyphens */
const validProjectName = fc
  .tuple(
    fc.stringOf(fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz'.split('')), { minLength: 1, maxLength: 1 }),
    fc.stringOf(fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789-'.split('')), { minLength: 0, maxLength: 12 })
  )
  .map(([first, rest]) => first + rest);

// --- Unit Tests: MFA Mapping ---

describe('RegionalStack - MFA Mapping', () => {
  it('MFA "required" maps to Cognito REQUIRED', () => {
    const config = createConfig({ mfa: 'required' });
    const template = synthesizeRegionalStack(config);

    template.hasResourceProperties('AWS::Cognito::UserPool', {
      MfaConfiguration: 'ON',
    });
  });

  it('MFA "optional" maps to Cognito OPTIONAL', () => {
    const config = createConfig({ mfa: 'optional' });
    const template = synthesizeRegionalStack(config);

    template.hasResourceProperties('AWS::Cognito::UserPool', {
      MfaConfiguration: 'OPTIONAL',
    });
  });

  it('MFA "off" maps to Cognito OFF', () => {
    const config = createConfig({ mfa: 'off' });
    const template = synthesizeRegionalStack(config);

    template.hasResourceProperties('AWS::Cognito::UserPool', {
      MfaConfiguration: 'OFF',
    });
  });
});

// --- Unit Tests: PreSignup Lambda Conditional ---

describe('RegionalStack - PreSignup Lambda Conditional', () => {
  it('PreSignup Lambda is NOT created when emailRestriction.enabled=false', () => {
    const config = createConfig({ emailRestriction: { enabled: false } });
    const template = synthesizeRegionalStack(config);

    // Only the Proxy Lambda should exist, not the PreSignup Lambda
    const lambdas = template.findResources('AWS::Lambda::Function');
    const lambdaNames = Object.values(lambdas).map(
      (r: any) => r.Properties?.FunctionName
    );
    expect(lambdaNames).not.toContain(expect.stringContaining('pre-signup'));
  });

  it('PreSignup Lambda IS created when emailRestriction.enabled=true', () => {
    const config = createConfig({
      emailRestriction: { enabled: true, allowedDomains: ['example.com'] },
    });
    const template = synthesizeRegionalStack(config);

    template.hasResourceProperties('AWS::Lambda::Function', {
      FunctionName: 'test-project-pre-signup',
    });
  });
});

// --- Property Test: Project Name Prefix (Property 3) ---

describe('Feature: cdk-open-source-refactor, Property 3: Project name prefix propagation', () => {
  it('for any valid project name, synthesized resource names contain the project name prefix', () => {
    /**
     * Validates: Requirements 5.2
     */
    fc.assert(
      fc.property(validProjectName, (projectName) => {
        const config = createConfig({ projectName });
        const app = new cdk.App();
        const stack = new RegionalStack(app, 'TestStack', {
          config,
          env: { region: 'us-east-1', account: '123456789012' },
        });
        const template = Template.fromStack(stack);

        // Check S3 bucket name contains project name prefix
        template.hasResourceProperties('AWS::S3::Bucket', {
          BucketName: `${projectName}-frontend-assets`,
        });

        // Check Cognito User Pool name contains project name prefix
        template.hasResourceProperties('AWS::Cognito::UserPool', {
          UserPoolName: `${projectName}-user-pool`,
        });

        // Check Proxy Lambda function name contains project name prefix
        template.hasResourceProperties('AWS::Lambda::Function', {
          FunctionName: `${projectName}-proxy`,
        });

        // Check API Gateway name contains project name prefix
        template.hasResourceProperties('AWS::ApiGateway::RestApi', {
          Name: `${projectName}-api`,
        });
      }),
      { numRuns: 100 }
    );
  });
});

// --- Snapshot Test ---

describe('RegionalStack - CDK Synthesis Snapshot', () => {
  it('produces consistent CloudFormation output', () => {
    const config = createConfig({
      projectName: 'snapshot-test',
      mfa: 'required',
      emailRestriction: { enabled: true, allowedDomains: ['example.com'] },
    });
    const template = synthesizeRegionalStack(config);

    expect(template.toJSON()).toMatchSnapshot();
  });
});
